### ISSUE TITLE
fcitx5-chewing does not show candidate window with libchewing 0.8.0 rc1

### ISSUE THREAD

**Issue by yan12125** [chewing/libchewing#504] opened 2024-04-28 09:30 UTC
**Describe the bug**
fcitx5-chewing should show a candidate window when I hit key Down, but it doesn't. That happens after I update libchewing from 0.7.0 to 0.8.0 rc1.

**To Reproduce**
1. Configure fcitx5-chewing
2. Type `1u4` (`ㄅㄧˋ`)
4. Hit key Down

**Expected behavior**
A candidate window is shown

**Screenshots**
(nothing there when I hit key Down)

**Platform (please complete the following information):**
 - OS: Arch Linux up-to-date
 - Desktop:  LXQt
 - IME: fcitx5-chewing 5.1.2
 - Version
     - 0.8.0 rc1, built with [this PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/libchewing/-/blob/d32e29f473547eef03e44c4128f42fc77d968bf8/PKGBUILD)
     - 0.7.0, from Arch Linux official packages (Rust not enabled, no issue with this version)

**Additional context**
It seems fcitx5-chewing [uses `chewing_cand_CheckDone`](https://github.com/fcitx/fcitx5-chewing/blob/5.1.2/src/eim.cpp#L614C10-L614C32) to decide whether to show the candidate window or not. gdb reports `chewing_cand_CheckDone` returns 0 when I hit key Down. That may be why I didn't see the candidate window.

/cc @wengxt this is related to fcitx5-chewing. It will be great if you can check if I understand fcitx5-chewing correctly or not.

**Comment by kanru** [comment] 2024-04-28 10:15
Current tests has coverage for `chewing_cand_CheckDone` so the issue is probably somewhere else.

I'm not sure if you can run fcitx5-chewing from console. If you can enable environment variable `RUST_LOG=debug` it should print some debug info.

**Comment by yan12125** [comment] 2024-04-28 10:35
Thanks! I can confirm #505 fixes the candidate window in fcitx5-chewing.

> I'm not sure if you can run fcitx5-chewing from console. If you can enable environment variable RUST_LOG=debug it should print some debug info.

Nice tip, I didn't know that. If you still need the log, I can paste the result of `RUST_LOG=debug fcitx5 -D --verbose default=5,chewing=5` here.

**Comment by kanru** [comment] 2024-04-28 10:45
So the C version of `chewing_cand_CheckDone` had a bug that... it always returns 1 after first input. This will only be fixed in the Rust version.

**Closed** 2024-04-28 10:50 UTC
Labels: bug

**Comment by yan12125** [comment] 2024-04-28 12:14
> So the C version of `chewing_cand_CheckDone` had a bug that... it always returns 0 after first input. This will only be fixed in the Rust version.

No problem! I will continue using the Rust version unless there is a big issue.

**Comment by yan12125** [comment] 2024-04-30 04:11
I noticed fcitx5-chewing moved away from `chewing_cand_CheckDone` via https://github.com/fcitx/fcitx5-chewing/commit/4411a3a813207389ce0931b0a9de981869932866. New fcitx5-chewing works fine with libchewing 0.7.0 (C version), while there is a new GUI issue with libchewing 0.8.0 rc1 (Rust version). I will try to check what's going on.
